language: php
sudo: false
git:
  submodules: false
cache:
  directories:
    - vendor
php:
  - 7.2.24
  - 7.4
install:
  - composer --no-interaction install
script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --dry-run -v --diff
